### ISSUE TITLE
click random in sequence gets same word every time

### ISSUE THREAD

**Issue by illionas** [dougsko/com.dougsko.diceware#2]
This is probably a minor issue since it is easily recognized. I still want to mention it.

If you hit the "random.org" button in quick succession (that is before it could load the value from random.org) it will put the same word into the list as many times as you have hit the button. E.g. I hit the button ten times without waiting for a result and afterwards it gave me "pout pout pout pout pout pout pout pout pout pout".

**Comment by dougsko** [comment]
Hi!

Thanks for the feedback.  I think what's happening is that random.org isn't able to supply new random numbers as fast as you can hit the button.  I'll look into adding a delay or maybe a queuing system for the requests in order to alleviate the issue.

**Comment by dougsko** [comment]
This was actually a UI issue and it should be fixed in the latest release.  Thanks again for the heads up!
