### ISSUE TITLE
Esperanto List issues

### ISSUE THREAD

**Issue by Koriban** [dougsko/com.dougsko.diceware#3]
Hello,
having issues with the included Esperanto list, when selected it uses one of the English lists, 
also the entry in the menu is misspelled 

thanks,
Sean

**Comment by dougsko** [comment]
Good catch.  I have the same spelling error in my controller which is causing this bug.  I'll get this fixed and push out an update shortly.  Thanks!

**Comment by dougsko** [comment]
Fixed.
