### ISSUE TITLE
Add the eyeware wordlist please.

### ISSUE THREAD

**Issue by WAR10CKfreeworld** [dougsko/com.dougsko.diceware#5]
I would like to have the eyeware wordlist implemented into this app. As a Lord of the Rings fan, I would like to generate passwords with words from the books.

Here is the list: https://github.com/nightsense/eyeware

It is recommended to use the eyeware8k list for computers. But that might take more time then the standard one which is readymade for import.

**Comment by dougsko** [comment]
Sure that's not a problem.  Stay tuned for an update.

**Comment by dougsko** [comment]
The eyeware dictionary has been added to the app and was deployed today.  You should see it in the store once google updates the listing.  Thanks for using Diceware!
